version: "3.9"
services:
  dev:
    build:
      context: .
    volumes:
      - .:/work
    tty: true
  postgres:
    image: postgres:14.5
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
