version: "3.9"
services:
  dev:
    build:
      context: .
    volumes:
      - .:/work
    tty: true

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./volumes/mysql/db:/var/lib/mysql
