POST http://localhost:3020/auth/login
content-type: application/json

{
    "id": "tes1",
    "password": "aaa"
}

POST http://localhost:3020/auth/add
content-type: application/json

{
    "email": "test2.gmail.com",
    "password": "aaa",
    "name": "taro"
}
