// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Auths", testAuths)
	t.Run("Workers", testWorkers)
}

func TestDelete(t *testing.T) {
	t.Run("Auths", testAuthsDelete)
	t.Run("Workers", testWorkersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Auths", testAuthsQueryDeleteAll)
	t.Run("Workers", testWorkersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Auths", testAuthsSliceDeleteAll)
	t.Run("Workers", testWorkersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Auths", testAuthsExists)
	t.Run("Workers", testWorkersExists)
}

func TestFind(t *testing.T) {
	t.Run("Auths", testAuthsFind)
	t.Run("Workers", testWorkersFind)
}

func TestBind(t *testing.T) {
	t.Run("Auths", testAuthsBind)
	t.Run("Workers", testWorkersBind)
}

func TestOne(t *testing.T) {
	t.Run("Auths", testAuthsOne)
	t.Run("Workers", testWorkersOne)
}

func TestAll(t *testing.T) {
	t.Run("Auths", testAuthsAll)
	t.Run("Workers", testWorkersAll)
}

func TestCount(t *testing.T) {
	t.Run("Auths", testAuthsCount)
	t.Run("Workers", testWorkersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Auths", testAuthsHooks)
	t.Run("Workers", testWorkersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Auths", testAuthsInsert)
	t.Run("Auths", testAuthsInsertWhitelist)
	t.Run("Workers", testWorkersInsert)
	t.Run("Workers", testWorkersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("AuthToWorkerUsingWorker", testAuthToOneWorkerUsingWorker)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {
	t.Run("WorkerToAuthUsingAuth", testWorkerOneToOneAuthUsingAuth)
}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("AuthToWorkerUsingAuth", testAuthToOneSetOpWorkerUsingWorker)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {
	t.Run("WorkerToAuthUsingAuth", testWorkerOneToOneSetOpAuthUsingAuth)
}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Auths", testAuthsReload)
	t.Run("Workers", testWorkersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Auths", testAuthsReloadAll)
	t.Run("Workers", testWorkersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Auths", testAuthsSelect)
	t.Run("Workers", testWorkersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Auths", testAuthsUpdate)
	t.Run("Workers", testWorkersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Auths", testAuthsSliceUpdateAll)
	t.Run("Workers", testWorkersSliceUpdateAll)
}
